AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer with Target Group

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    Description: Environment name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 1 ID

  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 2 ID

  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ALB Security Group ID

  Ec2Instance1Id:
    Type: AWS::EC2::Instance::Id
    Description: EC2 Instance 1 ID

  Ec2Instance2Id:
    Type: AWS::EC2::Instance::Id
    Description: EC2 Instance 2 ID

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # Application Load Balancer
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-alb
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-alb
        - Key: Environment
          Value: !Ref Environment

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-tg
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: instance
      Targets:
        - Id: !Ref Ec2Instance1Id
          Port: 80
        - Id: !Ref Ec2Instance2Id
          Port: 80
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-tg
        - Key: Environment
          Value: !Ref Environment

  # HTTP Listener
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  AlbDnsName:
    Description: ALB DNS Name
    Value: !GetAtt Alb.DNSName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-alb-dns

  AlbArn:
    Description: ALB ARN
    Value: !Ref Alb
    Export:
      Name: !Sub ${ProjectName}-${Environment}-alb-arn

  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-tg-arn