AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer with Target Group

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    Description: Environment name

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # Application Load Balancer
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-alb
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-alb-sg-id
      Subnets:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-public-subnet-1-id
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-public-subnet-2-id
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-alb
        - Key: Environment
          Value: !Ref Environment

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-tg
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-vpc-id
      TargetType: instance
      Targets:
        - Id: !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-ec2-1-id
          Port: 80
        - Id: !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-ec2-2-id
          Port: 80
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-tg
        - Key: Environment
          Value: !Ref Environment

  # HTTP Listener
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  AlbDnsName:
    Description: ALB DNS Name
    Value: !GetAtt Alb.DNSName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-alb-dns

  AlbArn:
    Description: ALB ARN
    Value: !Ref Alb
    Export:
      Name: !Sub ${ProjectName}-${Environment}-alb-arn

  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-tg-arn