AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instances with IAM role for Session Manager

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    Description: Environment name

  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # IAM Role for EC2 (Session Manager)
  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${Environment}-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-ec2-role
        - Key: Environment
          Value: !Ref Environment

  # Instance Profile
  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ProjectName}-${Environment}-ec2-profile
      Roles:
        - !Ref Ec2Role

  # EC2 Instance 1
  Ec2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      InstanceType: !Ref InstanceType
      SubnetId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-1-id
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-ec2-sg-id
      IamInstanceProfile: !Ref Ec2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from EC2 - Instance 1</h1><p>Host: $(hostname)</p>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-ec2-1
        - Key: Environment
          Value: !Ref Environment

  # EC2 Instance 2
  Ec2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      InstanceType: !Ref InstanceType
      SubnetId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-2-id
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-ec2-sg-id
      IamInstanceProfile: !Ref Ec2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from EC2 - Instance 2</h1><p>Host: $(hostname)</p>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-ec2-2
        - Key: Environment
          Value: !Ref Environment

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  Ec2Instance1Id:
    Description: EC2 Instance 1 ID
    Value: !Ref Ec2Instance1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ec2-1-id

  Ec2Instance2Id:
    Description: EC2 Instance 2 ID
    Value: !Ref Ec2Instance2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ec2-2-id

  Ec2Instance1PrivateIp:
    Description: EC2 Instance 1 Private IP
    Value: !GetAtt Ec2Instance1.PrivateIp
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ec2-1-private-ip

  Ec2Instance2PrivateIp:
    Description: EC2 Instance 2 Private IP
    Value: !GetAtt Ec2Instance2.PrivateIp
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ec2-2-private-ip