AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL instance in Private DB Subnet

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    Description: Environment name

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: RDS instance class

  DBAllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage in GB

  DBName:
    Type: String
    Default: appdb
    Description: Database name

  DBUsername:
    Type: String
    Default: dbadmin
    Description: Master username

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master password (min 8 characters)

  MultiAZ:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable Multi-AZ deployment

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${ProjectName}-${Environment}-db-subnet
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-db-subnet-1-id
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-db-subnet-2-id
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-subnet
        - Key: Environment
          Value: !Ref Environment

  # RDS Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-${Environment}-db
      Engine: postgres
      EngineVersion: '15.12'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      MaxAllocatedStorage: 100
      StorageType: gp3
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-rds-sg-id
      MultiAZ: !Ref MultiAZ
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 03:00-04:00
      PreferredMaintenanceWindow: Mon:04:00-Mon:05:00
      PubliclyAccessible: false
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db
        - Key: Environment
          Value: !Ref Environment

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  DBEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-endpoint

  DBPort:
    Description: RDS Port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-port

  DBName:
    Description: Database Name
    Value: !Ref DBName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-db-name