AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Endpoints for SSM and S3

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    Description: Environment name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  PrivateWebApSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private WebAP Subnet 1 ID

  PrivateWebApSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Private WebAP Subnet 2 ID

  PrivateWebApRouteTableId:
    Type: String
    Description: Private WebAP Route Table ID

  VpcEndpointSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: VPC Endpoint Security Group ID

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # SSM Endpoint
  SsmEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateWebApSubnet1Id
        - !Ref PrivateWebApSubnet2Id
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true

  # SSM Messages Endpoint
  SsmMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateWebApSubnet1Id
        - !Ref PrivateWebApSubnet2Id
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true

  # EC2 Messages Endpoint
  Ec2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateWebApSubnet1Id
        - !Ref PrivateWebApSubnet2Id
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true

  # S3 Endpoint (Gateway type - free)
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateWebApRouteTableId

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  SsmEndpointId:
    Description: SSM Endpoint ID
    Value: !Ref SsmEndpoint
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ssm-endpoint-id

  S3EndpointId:
    Description: S3 Endpoint ID
    Value: !Ref S3Endpoint
    Export:
      Name: !Sub ${ProjectName}-${Environment}-s3-endpoint-id