AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Endpoints for SSM and S3

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    Description: Environment name

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # SSM Endpoint
  SsmEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-vpc-id
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-1-id
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-2-id
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-vpce-sg-id
      PrivateDnsEnabled: true

  # SSM Messages Endpoint
  SsmMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-vpc-id
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-1-id
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-2-id
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-vpce-sg-id
      PrivateDnsEnabled: true

  # EC2 Messages Endpoint
  Ec2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-vpc-id
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-1-id
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-webap-subnet-2-id
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-vpce-sg-id
      PrivateDnsEnabled: true

  # S3 Endpoint (Gateway type - free)
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-vpc-id
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      RouteTableIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-private-webap-rt-id

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  SsmEndpointId:
    Description: SSM Endpoint ID
    Value: !Ref SsmEndpoint
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ssm-endpoint-id

  S3EndpointId:
    Description: S3 Endpoint ID
    Value: !Ref S3Endpoint
    Export:
      Name: !Sub ${ProjectName}-${Environment}-s3-endpoint-id