AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with 3-tier subnet architecture (Public/WebAP/DB)

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for VPC

  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for Public Subnet 1

  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for Public Subnet 2

  PrivateWebApSubnet1Cidr:
    Type: String
    Default: 10.0.11.0/24
    Description: CIDR block for Private WebAP Subnet 1

  PrivateWebApSubnet2Cidr:
    Type: String
    Default: 10.0.12.0/24
    Description: CIDR block for Private WebAP Subnet 2

  PrivateDbSubnet1Cidr:
    Type: String
    Default: 10.0.21.0/24
    Description: CIDR block for Private DB Subnet 1

  PrivateDbSubnet2Cidr:
    Type: String
    Default: 10.0.22.0/24
    Description: CIDR block for Private DB Subnet 2

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-vpc
        - Key: Environment
          Value: !Ref Environment

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-igw
        - Key: Environment
          Value: !Ref Environment

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-public-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Public

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-public-2
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Public

  # Private WebAP Subnets
  PrivateWebApSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateWebApSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-private-webap-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private_WebAP

  PrivateWebApSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateWebApSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-private-webap-2
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private_WebAP

  # Private DB Subnets
  PrivateDbSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateDbSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-private-db-1
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private_DB

  PrivateDbSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateDbSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-private-db-2
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private_DB

  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-public-rt
        - Key: Environment
          Value: !Ref Environment

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Private WebAP Route Table
  PrivateWebApRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-private-webap-rt
        - Key: Environment
          Value: !Ref Environment

  PrivateWebApSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateWebApSubnet1
      RouteTableId: !Ref PrivateWebApRouteTable

  PrivateWebApSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateWebApSubnet2
      RouteTableId: !Ref PrivateWebApRouteTable

  # Private DB Route Table
  PrivateDbRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-private-db-rt
        - Key: Environment
          Value: !Ref Environment

  PrivateDbSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateDbSubnet1
      RouteTableId: !Ref PrivateDbRouteTable

  PrivateDbSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateDbSubnet2
      RouteTableId: !Ref PrivateDbRouteTable

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub ${ProjectName}-${Environment}-vpc-id

  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-public-subnet-1-id

  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-public-subnet-2-id

  PrivateWebApSubnet1Id:
    Description: Private WebAP Subnet 1 ID
    Value: !Ref PrivateWebApSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-private-webap-subnet-1-id

  PrivateWebApSubnet2Id:
    Description: Private WebAP Subnet 2 ID
    Value: !Ref PrivateWebApSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-private-webap-subnet-2-id

  PrivateDbSubnet1Id:
    Description: Private DB Subnet 1 ID
    Value: !Ref PrivateDbSubnet1
    Export:
      Name: !Sub ${ProjectName}-${Environment}-private-db-subnet-1-id

  PrivateDbSubnet2Id:
    Description: Private DB Subnet 2 ID
    Value: !Ref PrivateDbSubnet2
    Export:
      Name: !Sub ${ProjectName}-${Environment}-private-db-subnet-2-id

  PrivateWebApRouteTableId:
    Description: Private WebAP Route Table ID
    Value: !Ref PrivateWebApRouteTable
    Export:
      Name: !Sub ${ProjectName}-${Environment}-private-webap-rt-id